services:
  - type: web
    name: qa-bot-api
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /docs

  - type: web
    name: qa-bot-frontend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GEMINI_API_KEY
        sync: false
